### ISSUE TITLE
Android Studio运行不了，求作者帮一下忙~~

### ISSUE THREAD

**Issue by ck76** [NICOLITE/HutHelper#1]
\HutHelper\appKey.properties (系统找不到指定的文件。)

提示这个错误。

**Comment by nicolite** [comment]
appKey里面是一些平台的key，暂时没有开放，如果确实有需要，可以告诉你需要怎么做

**Comment by ck76** [comment]
我还是一个小白白，如果不gradle成功的话，没有预览图光看代码对于我来说很费劲，想要学习一下，仅供学习，没有其他用途，如果可以的话当然很好，谢谢作者:)

**Comment by ck76** [comment]
对了楼主能不能放出来一个测试账号，要不然都下载完了用不了你的APP:)

**Comment by nicolite** [comment]
我过几天改改，弄个可编译的开源版

**Comment by nicolite** [comment]
现在可以编译了
